class Strings:
    PROCESS = '进程'
    PROCESS_ID = f'{PROCESS}标识符'
    PROCESS_STATE = f'{PROCESS}状态'
    PROCESS_TYPE = f'{PROCESS}类型'
    PROCESS_REMAINING_TIME = '剩余时间'
    WINDOW_TITLE = f'{PROCESS}调度模拟-生产者/消费者模型'
    PAUSE_RESUME = '暂停/继续'
    NEXT_TURN = '下一时间点'
    RESET = '重置'
    PAUSE_RESUME_KEY = 'Ctrl+P'
    NEXT_TURN_KEY = 'Ctrl+N'
    RESET_KEY = 'Ctrl+R'
    CREATE_PROCESS = f'创建{PROCESS}'
    SHOW_LOG = '查看日志'
    RUNNABLE = '运行'
    BLOCKED = '阻塞'
    PROCESS_TABLE = f'{PROCESS}表'
    RUNNABLE_QUEUE = f'{RUNNABLE}队列'
    BLOCKED_QUEUE = f'{BLOCKED}队列'
    CURRENT_TIME = '当前时间点'
    CURRENT_PROCESS_ID = f'当前{PROCESS_ID}'
    ITEM_COUNT = '库存量'


class Templates:
    CURRENT_TIME = Strings.CURRENT_TIME + ': {}'
    CURRENT_PROCESS_ID = Strings.CURRENT_PROCESS_ID + ': {}'
    ITEM_COUNT = Strings.ITEM_COUNT + ': {}'
