class Strings:
    PROCESS = '进程'
    PRODUCER_EN = 'producer'
    CONSUMER_EN = 'consumer'
    PROCESS_ID = f'{PROCESS}标识符'
    PROCESS_STATE = f'{PROCESS}状态'
    PROCESS_TYPE = f'{PROCESS}类型'
    PROCESS_REMAINING_TIME = '剩余时间'
    PAUSE = '暂停'
    RESUME = '继续'
    NEXT_TURN = '下一时间点'
    RESET = '重置'
    PAUSE_RESUME_KEY = 'Ctrl+P'
    NEXT_TURN_KEY = 'Ctrl+N'
    RESET_KEY = 'Ctrl+R'
    SHOW_LOG_KEY = 'Ctrl+L'
    CREATE_PROCESS = f'创建{PROCESS}'
    SHOW_LOG = '查看日志'
    BURST_TIME_INPUT_TIP = '进程运行时间（秒）'

    READY = '就绪'
    RUNNING = '运行'
    BLOCKED = '阻塞'
    FINISHED = '完成'

    RUNNING_BLOCKED = '库存不足'
    RUNNING_READY = '时间片到'
    READY_RUNNING = '调度运行'
    BLOCKED_READY = '库存变化'
    RUNNING_FINISHED = '任务完成'

    PROCESS_TABLE = f'{PROCESS}表'
    RUNNABLE_QUEUE = f'{READY}队列'
    BLOCKED_QUEUE = f'{BLOCKED}队列'
    CURRENT_TIME = '当前时间点'
    CURRENT_PROCESS_ID = f'当前{PROCESS_ID}'
    ITEM_COUNT = '库存'
    EMPTY_INVENTORY = f'{ITEM_COUNT}为空'
    NO_RUNNABLE_PROCESS = f'无可{RUNNING}{PROCESS}'

    LOG_DIALOG_TITLE = '运行日志'
    WINDOW_TITLE = f'{PROCESS}调度模拟-生产者/消费者模型'


class Templates:
    CURRENT_TIME = Strings.CURRENT_TIME + ': {}'
    CURRENT_PROCESS_ID = Strings.CURRENT_PROCESS_ID + ': {}'
    ITEM_COUNT = Strings.ITEM_COUNT + ': {}'
